### ISSUE TITLE
[FEATURE] - Webhook support for Twitch

### ISSUE THREAD

**Issue by camjac251** [dangeroustech/StreamDL#78]
Would it be possible to support this checking system of streams going live on Twitch? I haven't been able to find a script that uses this system. All monitoring seems to happen through a cron schedule system with all of the scripts.

This could solve the problem of checking the API in an interval timing out when there are too many users to check and also the beginning of the recording missing due to having to set a slower interval to combat the timeouts.

This is the info I've been able to find on it
https://dev.twitch.tv/docs/api/reference/#get-streams
https://discuss.dev.twitch.tv/t/webhook-twitch-start/21010
https://dev.twitch.tv/docs/api/webhooks-guide

**Comment by biodrone** [comment]
Seems like a great idea! I'll have to add some OAuth logic to support user tokens and the Twitch API still does have rate limits for that method, they're just based on token not IP Address. Either way, I'll definitely look into it!

**Comment by camjac251** [comment]
Oh cool thank you. Is there a way to see the rate limits? I was hoping to monitor 15 or so streamers.

**Comment by biodrone** [comment]
[API docs](https://dev.twitch.tv/docs/api/guide#rate-limits) reckon with a good user token it allows 800 requests a minute... I think that should be fine 😁

**Comment by camjac251** [comment]
I think this might be a bad feature now to have. From what I'm seeing, webhooks are nowhere near instant and often times longer than a minute. It would be best to test of course but it might be a lost cause.
I might have a better alternative however.
`streamlink -j twitch.tv/channel` 
> `-j, --json`
> Output JSON representations instead of the normal text output.
> Useful for external scripting.

This supposedly is just a few seconds behind. I tested going live and ran this a few times, it reports whether a channel is live or not with `"error": "No playable streams found on this URL:` or `"streams": {` listing.
If this was run every second than it might be easier than with the Twitch API.

**Comment by biodrone** [comment]
Yeah when looking into the webhooks aspect Twitch now only support OAuth which pretty majorly changes the structure of the project and requires registration and all sorts of other nonsense.

Streamlink looks interesting though, I'll have a play around with it. I'd imagine it has to check Twitch in the same way but we'll see. What error were you getting when you checked too often?

**Comment by camjac251** [comment]
I can't remember since it was so long ago and I've just been using a higher one now. I think you may want to use streamlink instead of youtube-dl since right now, it's the only one working.

youtube-dl is broken right now with twitch. As I understand it, they deprecated v3 of the api today and youtube-dl was still using it.

**Comment by biodrone** [comment]
Ahh wonderful, good old Twitch. That new API didn't seem too friendly to programs of that sort. There's a community patch that I'll pull in later on tonight, I imagine ytdl will fix it pretty quickly anyhow.

**Comment by camjac251** [comment]
The pull request patch should work judging by the people who've tried it. But I would not want to use youtube-dl after this for Twitch stuff given how it uses long depecrated APIs and ignored upgrading.

**Comment by biodrone** [comment]
Just keep in mind that they also support hundreds of other sites. Plus, having one dependency per site for streamdl is unnecessary overhead imo.

**Comment by camjac251** [comment]
I think streamlink and youtube-dl support just about the same for live streams as far as I'm aware. 
The first few that streamlink has, youtube-dl doesn't.
Youtube-dl is more for vods I think. streamlink focuses on live.
 
https://streamlink.github.io/plugin_matrix.html#plugin-matrix
https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md

**Comment by biodrone** [comment]
Streamdl is currently a bit of both but I'm think I'll default to streamlink, just sorting the file formatting and testing the recursion and it should be ready.

**Comment by camjac251** [comment]
I came across this which was interesting
https://github.com/EnterGin/Auto-Stream-Recording-Twitch/blob/7aa9becd3cea626ee5cd93b6b3fa55ff2634baf0/Auto_Recording_Twitch.py#L315

Although testing `--retry-streams 1` alone had some issues, which might also affect other streams when they start up. You lose about 3-4 seconds from when streamlink starts "recording" using the above, from beginning and end.
However using something like this works really well. But in the wiki it says this is not recommend for streams that do not have low latency enabled as it could cause buffering, although if it's buffered and cached, couldn't it catch up?
`streamlink --hls-live-edge 1 --hls-segment-threads 1 --twitch-disable-hosting twitch.tv/user best --retry-streams 1 -o recorded_filename.mp4`
